import os
import re
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# directory where autocannon outputs are stored
RESULT_DIR = "../results"

# files generated by the benchmarks
FILES = {
    "Login": "login_results.txt",
    "Documents": "documents_results.txt",
    "Query (RAG)": "query_results.txt"
}

data = []


def extract_metrics(filepath):
    """
    Extract latency and req/sec from autocannon output
    """

    latency = None
    reqsec = None

    with open(filepath, "r") as f:
        text = f.read()

    latency_match = re.search(r"Latency\s+([\d\.]+)\s+ms", text)
    req_match = re.search(r"Req/Sec\s+([\d\.]+)", text)

    if latency_match:
        latency = float(latency_match.group(1))

    if req_match:
        reqsec = float(req_match.group(1))

    return latency, reqsec


for endpoint, filename in FILES.items():

    path = os.path.join(RESULT_DIR, filename)

    if not os.path.exists(path):
        print(f"Skipping missing file: {filename}")
        continue

    latency, reqsec = extract_metrics(path)

    if latency is None or reqsec is None:
        print(f"Could not parse metrics from {filename}")
        continue

    data.append({
        "Endpoint": endpoint,
        "Latency_ms": latency,
        "Requests_per_sec": reqsec
    })


if not data:
    print("No valid benchmark results found.")
    exit()

df = pd.DataFrame(data)

# styling for research graphs
sns.set_theme(style="darkgrid")

# -------- Latency Graph --------

plt.figure(figsize=(8, 5))
sns.barplot(data=df, x="Endpoint", y="Latency_ms")

plt.title("API Endpoint Latency Comparison")
plt.ylabel("Latency (ms)")
plt.xlabel("Endpoint")

plt.tight_layout()

latency_output = os.path.join(RESULT_DIR, "latency_graph.png")
plt.savefig(latency_output, dpi=300)

plt.close()


# -------- Throughput Graph --------

plt.figure(figsize=(8, 5))
sns.barplot(data=df, x="Endpoint", y="Requests_per_sec")

plt.title("API Endpoint Throughput Comparison")
plt.ylabel("Requests per Second")
plt.xlabel("Endpoint")

plt.tight_layout()

throughput_output = os.path.join(RESULT_DIR, "throughput_graph.png")
plt.savefig(throughput_output, dpi=300)

plt.close()


# -------- Combined Performance Table --------

table_output = os.path.join(RESULT_DIR, "benchmark_summary.csv")
df.to_csv(table_output, index=False)


print("\nGraphs and summary generated successfully.")
print(f"Latency graph: {latency_output}")
print(f"Throughput graph: {throughput_output}")
print(f"Summary table: {table_output}")